apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: weather-app-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/muhammadsohaib56/weather-app.git
  ref:
    branch: main

