apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: weather-app-deployment
  namespace: flux-system
spec:
  interval: 10m
  path: .  # Set path to the current directory where your manifests are located
  prune: true
  sourceRef:
    kind: GitRepository
    name: weather-app-repo
  targetNamespace: default
